pipeline{

  agent any{

  stages{
    stage("build"){

      steps{
          echo 'building the applications...'
      }
    }

    stage("Test"){

      steps{
          echo 'testing the applications...'
      }
    }
    stage("deploy"){

      steps{

        echo 'deplying the applications'
      }
    }
  }
  }
}
